config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => {:omniauth_callbacks => "callbacks"}

  root 'welcome#index'

    get 'projects/:id/similars' => 'projects#similars', as: :projects_similars

    resources :projects
    resources :categories 
    resources :ratings
    resources :comments
    resources :brands
    resources :users do
      resources :projects
      member do
        get :following, :followers
      end
    end
    resources :relationships, only: [:create, :destroy]

end

app/models/project.rb
class Project < ActiveRecord::Base

  mount_uploader :image, ProjectImageUploader
  
  has_many :comments
  has_many :ratings
  has_and_belongs_to_many :categories
  has_and_belongs_to_many :brands
  belongs_to :user

  # self association (to assign projects that are similar to each other)
  has_many :similarities, foreign_key: "similar_id", dependent: :destroy
  has_many :reverse_similarities, class_name: "Similarity", foreign_key: "similee_id", dependent: :destroy
  has_many :projects, through: :similarities, source: "similee"
  
  # letsrate_rateable

  def similar_projects
    self.projects.where.not(id: self.id)
  end
  
  def average_rating
    average = ratings.inject(0.0){ |sum, el| sum + el.value }.to_f / ratings.size
    average.round(2)
  end

  validates :title, :content, presence: :true

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
    respond_to do |format|
      format.html
      format.json { render json: @projects }
    end
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    @project = Project.new
  end

  def create

    @project = Project.new project_params
    @project.user_id = current_user.id
    if @project.video
      @project.video = @project.video.sub(/.*?=/, '')
      @project.save
    end
    redirect_to projects_path
  end

  def similars
    @project = Project.find(params[:id])
    # redirect_to project_path(@project) if @project.update
    # else render project_similar(@project)
    # render json: @project, status: :created
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    @project.update project_params
    # head :no_content, status: :ok  //no need for this right now as doing a traditional rails redirect
    redirect_to project_path(@project)
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to projects_path
  end

  def project_params
    params.require(:project).permit(:user_id, :title, :content, :video, :image, { project_ids: [] })
  end
end

app/views/projects/_form.html.haml
.background
  .container#form
    %h1 Tell us about your idea
    = simple_form_for @project do |f|
      - if @project.errors.any?
        #error_explanation 
          %ul
            - @project.errors.full_messages.each do |message|
              %li= message
      %p= f.text_field :title, placeholder: "What's it called?", id: "input"
      %p= f.file_field :image
      %p= f.text_field :video, placeholder: "Copy-paste a youtube link of your idea here!"
      %p= f.text_area :content, placeholder: "Tell us a bit more!", id: "input"
      %p= f.association :categories, as: :check_boxes, label:"Pick categories it falls under"
      %p= f.association :brands, as: :check_boxes, label: "Pick famous brands your project would ressemble"
      %p= f.submit 'Share your idea with the world!', id: "input"

app/views/projects/edit.html.haml
= render 'form'

app/views/projects/index.html.haml
.projects-container
  %h1 Million $ Ideas
  =image_tag "lightbulb.svg"
  - if user_signed_in?
    = link_to '+ Share your own idea!', new_project_path
  - else 
    .message you must create an account to share a new idea!
  .container#projects

app/views/projects/new.html.haml
= render 'form'

app/views/projects/show.html.haml
.project-page

  .project-header
    %h1= @project.title.upcase
    = image_tag 'lightbulb.svg',class: 'image'
    = image_tag(@project.image.project_show.url, class: 'project-image')
    %p By <i>#{@project.user.firstname} #{@project.user.lastname}</i>
    #categories
      - @project.categories.each do |category|
        .category-thumbnail= link_to '#'+category.name, category_path(category)
  
  - if @project.video?
    %iframe{:height => "315", :src => "http://www.youtube.com/embed/#{@project.video}", :width => "400"}

  %p= @project.content
  .rating
    .rating-box
      .star#one{data:{rating:1}}
      .star#two{data:{rating:2}}
      .star#three{data:{rating:3}}
      .star#four{data:{rating:4}}
      .star#five{data:{rating:5}}
    .notify

    .average-rating{data:{rating:@project.average_rating}}
      %p= "Average rating: #{@project.average_rating}"

  - if user_signed_in?
    %input#comment-box{ data: {project_id: @project.id }, placeholder: "Comment on this project!", title: "Press Enter to Submit" }
  - else 
    .message You must be signed in to comment
  %ul#comments{data:{projectid:params[:id]}}
  
  #similars
    = link_to 'Know a similar Project?', projects_similars_path(@project)
    %p Similar Projects
    - @project.similar_projects.each do |project|
      .similar= link_to project.title, project_path(project)

.footer
  - if user_signed_in?
    - if @project.user_id = current_user.id
      = link_to 'Edit', edit_project_path(@project)
      = link_to 'Delete', project_path(@project), method: :delete

  = link_to 'Back', projects_path

app/views/projects/similars.html.haml
%h1 Which projects do you reckon this one is similar to?
= simple_form_for @project do |f|
  =f.association :projects, as: :check_boxes
  =f.submit "Confirm"