config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => {:omniauth_callbacks => "callbacks"}

  root 'welcome#index'

    get 'projects/:id/similars' => 'projects#similars', as: :projects_similars

    resources :projects
    resources :categories 
    resources :ratings
    resources :comments
    resources :brands
    resources :users do
      resources :projects
      member do
        get :following, :followers
      end
    end
    resources :relationships, only: [:create, :destroy]

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Can
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    %script{:charset => "utf-8", :src => "/assets/jquery.easing.1.3.js"}
    %script{:charset => "utf-8", :src => "/assets/jquery.jSlots.js"}
    %link{:rel => "stylesheet", :href => "http://fonts.googleapis.com/css?family=News+Cycle"}/
    %link{:rel => "stylesheet", :href => "http://fonts.googleapis.com/css?family=Coming+Soon"}/
    = csrf_meta_tags
  %body
    %header.animated-nav
      %input{placeholder: "Search", type: "text"}
      %h1
        = link_to('uCAN', "/")
      %p.notice= notice
      %p.alert= alert
      - if user_signed_in?
        %ul
          %li
            = link_to 'Ideas!', projects_path
          %li
            = link_to 'Share An Idea', new_project_path 
          %li
            = link_to 'Creatives', users_path
          %li
            = link_to 'Categories', categories_path
          %li
            = link_to 'IsLikes', brands_path
          %li
            = link_to 'My Profile', user_path(current_user)
          %li
            = link_to 'Log Out', destroy_user_session_path, method: :delete
      - else
        %ul
          %li
            %a{href: "/projects"} Ideas
          %li
            %a{href: "#{new_user_session_path}"} Sign In
          %li
            %a{href: "#{new_user_registration_path}"} Register
    .content_container    
    = yield